version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: photoApp
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: photo-app
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass123
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs:
    build: .
    container_name: nestjs-app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: dev
      DB_PASSWORD: pass123
      DB_NAME: photo-app
    ports:
      - '3000:3000'
    depends_on:
      - mysql

volumes:
  mysql-data:
