version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: photoApp
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: photo-app
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass123
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
